{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}

-- | This module provides some simple pretty-printing output verification tests.
-- This amounts to spot-checking a few places in the pretty printing that are
-- examined by hand: in general, it its much more effective to do round-trip
-- testing using AST's parsed from bitcode generated by actual programs, which is
-- what occurs in the llvm-pretty-bc-parser package (i.e. much more comprehensive
-- testing is deferred to the llvm-pretty-bc-parser package, which might then
-- reveal issues that need to be fixed in this llvm-pretty package).

module Output ( tests ) where

import           Control.Monad ( unless )
import           Data.Functor.Identity (Identity(..))
import qualified Data.Text as T
import           GHC.Float (castWord32ToFloat, castWord64ToDouble)
import qualified Test.Tasty as Tasty
import           Test.Tasty.HUnit
import qualified Text.Parsec as Parsec
import qualified Text.PrettyPrint as PP

import           Text.LLVM.AST
import           Text.LLVM.Labels (relabel)
import           Text.LLVM.Parser (pPrimType)
import           Text.LLVM.PP

import           TQQDefs

tests :: Tasty.TestTree
tests = Tasty.testGroup "LLVM pretty-printing output tests"
  $ let -- s1 is a non-sensical construct whose primary intention is to hold two
        -- sub-structures that change their pretty representations at different
        -- LLVM versions.  The pretty output will be checked at different LLVM
        -- versions to ensure that the desired version-specific changes in the
        -- output are seen.
        s1, s2 :: Stmt
        s1 = Effect
             (GEP [GEP_Inbounds] (Alias (Ident "hi")) (Typed Opaque dcu) [])
             mempty []
        s2 = Effect (Load PtrOpaque (Typed Opaque ValNull) Nothing Nothing)
             mempty
             [ ("location", ValMdLoc $ DebugLoc { dlLine = 12
                                                , dlCol = 34
                                                , dlScope = ValMdRef 5
                                                , dlIA = Nothing
                                                , dlImplicit = True
                                                , dlAtomGroup = 0
                                                , dlAtomRank = 0 })
             ]
        s3 = Effect
               (IndirectBr
               (Typed PtrOpaque (ValIdent "addr"))
               [Named "hello", Named "world"])
               [] []
        dcu :: Value
        dcu = ValMd
              $ ValMdDebugInfo
              $ DebugInfoCompileUnit
              $ DICompileUnit { dicuLanguage = 12
                              , dicuFile = Nothing
                              , dicuProducer = Just "llvm-pretty-test"
                              , dicuIsOptimized = True
                              , dicuFlags = Just "some flags"
                              , dicuRuntimeVersion = 3
                              , dicuSplitDebugFilename = Nothing
                              , dicuEmissionKind = 1
                              , dicuEnums = Just dtt
                              , dicuRetainedTypes = Nothing
                              , dicuSubprograms = Nothing
                              , dicuGlobals = Nothing
                              , dicuImports = Nothing
                              , dicuMacros = Nothing
                              , dicuDWOId = 2
                              , dicuSplitDebugInlining = False
                              , dicuDebugInfoForProf = True
                              , dicuNameTableKind = 4
                              , dicuRangesBaseAddress = True
                              , dicuSysRoot = Just "the root"
                              , dicuSDK = Just "SDK"
                              , dicuSourceLanguageVersion = 0
                              }
        dtt = ValMdDebugInfo
              $ DebugInfoTemplateTypeParameter
              $ DITemplateTypeParameter { dittpName = Just "ttp"
                                        , dittpType = Nothing
                                        , dittpIsDefault = Just True
                                        }
        blk1 = BasicBlock { bbLabel = Just $ Named $ Ident "blk1"
                          , bbStmts =
                            [ Result (Ident "r1") (Comment "insanity follows...") mempty []
                            , Effect (Jump $ Named $ Ident "blk1") mempty []
                            , Result (Ident "oh no") RetVoid mempty []
                            , Effect (Br (Typed (PrimType Metadata) ValZeroInit) (Anon 3) (Named "oh no")) mempty []
                            ]
                          }
        blk2 = BasicBlock { bbLabel = Just $ Anon 123
                          , bbStmts = []
                          }
        ppToText = T.pack
                   -- render with a line-length of 30 to encourage wrapping on
                   -- most list elements or arguments for consistent output to
                   -- verify against any changes.
                   . PP.renderStyle (PP.Style PP.PageMode 30 1.0)
  in
  [
    testCase "Stmt 1, LLVM 3.5" $
    assertEqLines [sq|
      ----
      getelementptr inbounds opaque !DICompileUnit(language: 12,
                                                   producer: "llvm-pretty-test",
                                                   isOptimized: true,
                                                   flags: "some flags",
                                                   runtimeVersion: 3,
                                                   emissionKind: 1,
                                                   enums: !DITemplateTypeParameter(name: ttp),
                                                   dwoId: 2,
                                                   splitDebugInlining: false,
                                                   debugInfoForProfiling: true,
                                                   nameTableKind: 4)
      ----
      |]
      (ppToText $ ppLLVM35 ppStmt s1)

  , testCase "Stmt 1, LLVM 3.7" $
    assertEqLines [sq|
      In LLVM 3.7, the GEP instruction output shows the additional type
      ----
      getelementptr inbounds %hi, opaque !DICompileUnit(language: 12,
                                                        producer: "llvm-pretty-test",
                                                        isOptimized: true,
                                                        flags: "some flags",
                                                        runtimeVersion: 3,
                                                        emissionKind: 1,
                                                        enums: !DITemplateTypeParameter(name: ttp),
                                                        dwoId: 2,
                                                        splitDebugInlining: false,
                                                        debugInfoForProfiling: true,
                                                        nameTableKind: 4)
      ----
      |]
      (ppToText $ ppLLVM37 ppStmt s1)

  , testCase "Stmt 1, LLVM 10" $
    assertEqLines (ppToText $ ppLLVM 10 $ ppStmt s1) [sq|
      No change from LLVM 3.7 through LLVM 10
      ----
      getelementptr inbounds %hi, opaque !DICompileUnit(language: 12,
                                                        producer: "llvm-pretty-test",
                                                        isOptimized: true,
                                                        flags: "some flags",
                                                        runtimeVersion: 3,
                                                        emissionKind: 1,
                                                        enums: !DITemplateTypeParameter(name: ttp),
                                                        dwoId: 2,
                                                        splitDebugInlining: false,
                                                        debugInfoForProfiling: true,
                                                        nameTableKind: 4)
      ----
      |]

  , testCase "Stmt 1, LLVM 11" $
    assertEqLines (ppToText $ ppLLVM 11 $ ppStmt s1) [sq|
      In LLVM 11, DICompileUnit adds rangesBaseAddress, sysroot, and sdk
      ----
      getelementptr inbounds %hi, opaque !DICompileUnit(language: 12,
                                                        producer: "llvm-pretty-test",
                                                        isOptimized: true,
                                                        flags: "some flags",
                                                        runtimeVersion: 3,
                                                        emissionKind: 1,
                                                        enums: !DITemplateTypeParameter(name: ttp),
                                                        dwoId: 2,
                                                        splitDebugInlining: false,
                                                        debugInfoForProfiling: true,
                                                        nameTableKind: 4,
                                                        rangesBaseAddress: true,
                                                        sysroot: "the root",
                                                        sdk: "SDK")
      ----
      |]

  , testCase "Stmt 1, LLVM 18" $
    assertEqLines (ppToText $ ppLLVM 18 $ ppStmt s1) [sq|
      Significant changes occur in LLVM 19; ensure that the output is as
      expected just prior to those changes to properly capture the
      inflection point.
      ----
      getelementptr inbounds %hi, opaque !DICompileUnit(language: 12,
                                                        producer: "llvm-pretty-test",
                                                        isOptimized: true,
                                                        flags: "some flags",
                                                        runtimeVersion: 3,
                                                        emissionKind: 1,
                                                        enums: !DITemplateTypeParameter(name: ttp),
                                                        dwoId: 2,
                                                        splitDebugInlining: false,
                                                        debugInfoForProfiling: true,
                                                        nameTableKind: 4,
                                                        rangesBaseAddress: true,
                                                        sysroot: "the root",
                                                        sdk: "SDK")
      ----
      |]

  , testCase "Stmt 1, LLVM 19" $
    assertEqLines (ppToText $ ppLLVM 19 $ ppStmt s1) [sq|
      In LLVM 19, the GEP instruction "inbounds" is no longer a boolean
      but a flag with multiple possible values (only one is checked here).
      ----
      getelementptr inbounds %hi, opaque !DICompileUnit(language: 12,
                                                        producer: "llvm-pretty-test",
                                                        isOptimized: true,
                                                        flags: "some flags",
                                                        runtimeVersion: 3,
                                                        emissionKind: 1,
                                                        enums: !DITemplateTypeParameter(name: ttp),
                                                        dwoId: 2,
                                                        splitDebugInlining: false,
                                                        debugInfoForProfiling: true,
                                                        nameTableKind: 4,
                                                        rangesBaseAddress: true,
                                                        sysroot: "the root",
                                                        sdk: "SDK")
      ----
      |]

  ------------------------------------------------------------

  , testCase "Stmt 2, LLVM 3.5" $
    assertEqLines [sq|
      ----
      load opaque null, !location !MDLocation(line: 12,
                                              column: 34,
                                              scope: !5, implicit)
      ----
      |]
      (ppToText $ ppLLVM35 ppStmt s2)

  , testCase "Stmt 2, LLVM 3.7" $
    assertEqLines [sq|
      Beginning in LLVM 3.7, the type is no longer implicit and is explicitly
      shown, and the DebugLoc metadata is DILocation instead of MDLocation
      ----
      load ptr, opaque null, !location !DILocation(line: 12,
                                                   column: 34,
                                                   scope: !5, implicit)
      ----
      |]
      (ppToText $ ppLLVM37 ppStmt s2)

  , testCase "Stmt 2, LLVM 10" $
    assertEqLines [sq|
      No change since LLVM 3.7
      ----
      load ptr, opaque null, !location !DILocation(line: 12,
                                                   column: 34,
                                                   scope: !5, implicit)
      ----
      |]
      (ppToText $ ppLLVM 10 $ ppStmt s2)

  ------------------------------------------------------------

  , testCase "Stmt 3" $
    assertEqLines [sq|
      `indirectbr` pretty-printing works as expected (#174)
      ----
      indirectbr ptr %addr, [ label %hello,
                              label %world ]
      ----
      |]
      (ppToText $ ppLLVM llvmVlatest $ ppStmt s3)

  ------------------------------------------------------------
  -- Verify named labels and label targets are emitted correctly

  , testCase "Blk 1, LLVM 3.5" $
    assertEqLines (ppToText $ ppLLVM35 ppBasicBlock blk1) [sq|
      --------
      blk1:
        %r1 = ; insanity follows...
        br label %blk1
        %"oh no" = ret void
        br metadata zeroinitializer, label %3, label %"oh no"
      --------
      |]

  , testCase "Blk 1, LLVM 3.7" $
    assertEqLines (ppToText $ ppLLVM37 ppBasicBlock blk1) [sq|
      --------
      blk1:
        %r1 = ; insanity follows...
        br label %blk1
        %"oh no" = ret void
        br metadata zeroinitializer, label %3, label %"oh no"
      --------
      |]

  ------------------------------------------------------------
  -- Verify anonymous labels are emitted correctly

  , testCase "Blk 2, LLVM 3.5" $
    assertEqLines (ppToText $ ppLLVM35 ppBasicBlock blk2) [sq|
      --------
      ; <label>: 123
      --------
      |]

  , testCase "Blk 2, LLVM 3.7" $
    assertEqLines (ppToText $ ppLLVM37 ppBasicBlock blk2) [sq|
      --------
      ; <label>: 123
      --------
      |]

  , testCase "Zero (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0x0000)))
      "0.0"

  , testCase "One (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0x3c00)))
      "1.0"

  , testCase "Two (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0x4000)))
      "2.0"

  , testCase "Positive Infinity (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0x7c00)))
      "0xH7c00"

  , testCase "Negative Infinity (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0xfc00)))
      "0xHfc00"

  , testCase "NaN (half float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValHalf (FPHalf 0x7c55)))
      "0xH7c55"

  , testCase "Zero (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0x0000)))
      "0.0"

  , testCase "One (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0x3f80)))
      "1.0"

  , testCase "Two (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0x4000)))
      "2.0"

  , testCase "Positive Infinity (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0x7f80)))
      "0xR7f80"

  , testCase "Negative Infinity (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0xff80)))
      "0xRff80"

  , testCase "NaN (bfloat)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValBFloat (FPBFloat 0x7f85)))
      "0xR7f85"

  , testCase "Positive Infinity (float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFloat (castWord32ToFloat 0x7F800000)))
      "0x7ff0000000000000"

  , testCase "Negative Infinity (float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFloat (castWord32ToFloat 0xFF800000)))
      "0xfff0000000000000"

  , testCase "NaN 1 (float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFloat (castWord32ToFloat 0x7FC00000)))
      "0x7ff8000000000000"

  , testCase "NaN 2 (float)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFloat (castWord32ToFloat 0x7FD00000)))
      "0x7ffa000000000000"

  , testCase "Positive Infinity (double)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValDouble (castWord64ToDouble 0x7FF0000000000000)))
      "0x7ff0000000000000"

  , testCase "Negative Infinity (double)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValDouble (castWord64ToDouble 0xFFF0000000000000)))
      "0xfff0000000000000"

  , testCase "NaN 1 (double)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValDouble (castWord64ToDouble 0x7FFC000000000000)))
      "0x7ffc000000000000"

  , testCase "NaN 2 (double)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValDouble (castWord64ToDouble 0x7FFD000000000000)))
      "0x7ffd000000000000"

  , testCase "Zero (FP80)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFP80 (FP80_LongDouble 0x0000 0x0000000000000000)))
      "0xK00000000000000000000"

  , testCase "Zero (FP128)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFP128 (FP128_LongDouble 0x0000000000000000 0x0000000000000000)))
      "0xL00000000000000000000000000000000"

  , testCase "Zero (FP128_PPC)" $
    assertEqLines
      (ppToText $ ppLLVM37 ppValue (ValFP128_PPC (FP128_PPC_DoubleDouble 0.0 0.0)))
      "0xM00000000000000000000000000000000"

  -- Windows SEH funclet pretty-printing spot-checks.  Full round-trip
  -- coverage through bitcode lives in llvm-pretty-bc-parser's disasm-test
  -- (seh-funclets.ll).

  , let ppWide = T.pack . PP.renderStyle (PP.Style PP.PageMode 200 1.0)
        tokTy = PrimType Token
        none0 = Typed tokTy ValZeroInit
        noneN = Typed tokTy ValNull
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        bb    = Named (Ident "handler") :: BlockLabel
        bbUnw = Named (Ident "unw")     :: BlockLabel
        bb2   = Named (Ident "h2")      :: BlockLabel
        argi  = Typed (PrimType (Integer 32)) (ValInteger 0)
        seh i = ppWide $ ppLLVM 19 $ ppInstr i
    in Tasty.testGroup "SEH funclet pretty-printing"
       [ testCase "cleanuppad within none (ValZeroInit)" $
         assertEqLines
           (seh (CleanupPad none0 []))
           "cleanuppad within none []"

       , testCase "cleanuppad within none (ValNull)" $
         assertEqLines
           (seh (CleanupPad noneN []))
           "cleanuppad within none []"

       , testCase "catchpad within <ssa-token>" $
         assertEqLines
           (seh (CatchPad tok [argi]))
           "catchpad within %cs [i32 0]"

       , testCase "catchret to label" $
         assertEqLines
           (seh (CatchRet tok bb))
           "catchret from %cs to label %handler"

       , testCase "cleanupret unwind to caller" $
         assertEqLines
           (seh (CleanupRet tok Nothing))
           "cleanupret from %cs unwind to caller"

       , testCase "cleanupret unwind label" $
         assertEqLines
           (seh (CleanupRet tok (Just bbUnw)))
           "cleanupret from %cs unwind label %unw"

       , testCase "catchswitch within none unwind to caller" $
         assertEqLines
           (seh (CatchSwitch none0 [bb] Nothing))
           "catchswitch within none [label %handler] unwind to caller"

       , testCase "catchswitch within token, multiple handlers, explicit unwind" $
         assertEqLines
           (seh (CatchSwitch tok [bb, bb2] (Just bbUnw)))
           "catchswitch within %cs [label %handler, label %h2] unwind label %unw"
       ]

  -- Operand bundle pretty-printing spot-checks.  Full round-trip
  -- coverage through bitcode lives in llvm-pretty-bc-parser's disasm-test
  -- (windows-seh-funclets.bc).

  , let ppWide = T.pack . PP.renderStyle (PP.Style PP.PageMode 200 1.0)
        tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        bb    = Named (Ident "ok")  :: BlockLabel
        bbUnw = Named (Ident "unw") :: BlockLabel
        fnTy  = FunTy (PrimType Void) [] False
        fnPtr = ValSymbol (Symbol "callee")
        funBd = OperandBundle "funclet" [tok]
        deopt = OperandBundle "deopt"   []
        bundle i = ppWide $ ppLLVM 19 $ ppInstr i
    in Tasty.testGroup "Operand bundle pretty-printing"
       [ testCase "Call with empty bundle list omits the brackets" $
         assertEqLines
           (bundle (Call False fnTy fnPtr [] []))
           "call void @callee()"

       , testCase "Call with funclet bundle" $
         assertEqLines
           (bundle (Call False fnTy fnPtr [] [funBd]))
           "call void @callee() [\"funclet\"(token %cs)]"

       , testCase "Call with multiple bundles" $
         assertEqLines
           (bundle (Call False fnTy fnPtr [] [funBd, deopt]))
           "call void @callee() [\"funclet\"(token %cs), \"deopt\"()]"

       , testCase "Invoke with funclet bundle (bundle precedes 'to'/'unwind')" $
         assertEqLines
           (bundle (Invoke (PrimType Void) fnPtr [] bb bbUnw [funBd]))
           "invoke void @callee() [\"funclet\"(token %cs)] to label %ok unwind label %unw"

       , testCase "Invoke with empty bundle list omits the brackets" $
         assertEqLines
           (bundle (Invoke (PrimType Void) fnPtr [] bb bbUnw []))
           "invoke void @callee() to label %ok unwind label %unw"
       ]

  , let ppWide = T.pack . PP.renderStyle (PP.Style PP.PageMode 200 1.0)
        -- A minimal Define with no body; we only render the signature
        -- via ppDefineSig.
        baseDef = Define
          { defLinkage     = Nothing
          , defVisibility  = Nothing
          , defRetType     = PrimType Void
          , defName        = Symbol "f"
          , defArgs        = []
          , defVarArgs     = False
          , defAttrs       = []
          , defSection     = Nothing
          , defGC          = Nothing
          , defBody        = []
          , defMetadata    = mempty
          , defComdat      = Nothing
          , defPersonality = Nothing
          }
        persFn = Typed PtrOpaque (ValSymbol (Symbol "__gxx_personality_v0"))
        sig d  = ppWide (ppLLVM 19 (ppDefineSig d))
    in Tasty.testGroup "Define personality clause"
       [ testCase "no personality omits the clause" $
         do let out = sig baseDef
            assertBool ("unexpected 'personality' in: " ++ T.unpack out)
                       (not ("personality" `T.isInfixOf` out))

       , testCase "Just personality emits the clause after gc/section" $
         assertEqLines
           (sig (baseDef { defPersonality = Just persFn }))
           "define void @f() personality ptr @__gxx_personality_v0"
       ]

  ----------------------------------------------------------------------
  -- Behavioural contracts for the new SEH constructors / bundle field.
  -- These are pure functions exposed by the AST and they have downstream
  -- consumers (CFG analyses, label-renaming passes), so a regression
  -- here would silently corrupt translation.  They are not exercised by
  -- the pretty-printing spot-checks above.

  , Tasty.testGroup "Token PrimType"
    [ testCase "ppPrimType Token" $
      assertEqLines
        (T.pack (PP.render (ppLLVM 19 (ppPrimType Token))))
        "token"

    , testCase "pPrimType parses \"token\"" $
      case Parsec.parse pPrimType "" "token" of
        Right Token -> return ()
        Right other -> assertFailure ("parsed wrong PrimType: " ++ show other)
        Left  err   -> assertFailure ("parse failed: " ++ show err)
    ]

  , let tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        bb    = Named (Ident "h")   :: BlockLabel
        bbUnw = Named (Ident "unw") :: BlockLabel
    in Tasty.testGroup "isTerminator for SEH instructions"
       [ testCase "CleanupRet is a terminator" $
         assertBool "" (isTerminator (CleanupRet tok Nothing))
       , testCase "CatchRet is a terminator" $
         assertBool "" (isTerminator (CatchRet tok bb))
       , testCase "CatchSwitch is a terminator" $
         assertBool "" (isTerminator (CatchSwitch tok [bb] (Just bbUnw)))
       , testCase "CleanupPad is NOT a terminator" $
         assertBool "" (not (isTerminator (CleanupPad tok [])))
       , testCase "CatchPad is NOT a terminator" $
         assertBool "" (not (isTerminator (CatchPad tok [])))
       ]

  , let tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        bbH   = Named (Ident "h")   :: BlockLabel
        bbH2  = Named (Ident "h2")  :: BlockLabel
        bbUnw = Named (Ident "unw") :: BlockLabel
        -- Build a one-statement basic block whose terminator is the
        -- supplied SEH instruction and ask brTargets what its successors
        -- are.  This is what downstream CFG construction relies on.
        bb i  = BasicBlock { bbLabel = Just (Named (Ident "entry"))
                           , bbStmts = [Effect i mempty []]
                           }
    in Tasty.testGroup "brTargets for SEH terminators"
       [ testCase "CatchRet has the catchret destination as its sole successor" $
         assertEqual ""
           [bbH]
           (brTargets (bb (CatchRet tok bbH)))
       , testCase "CatchSwitch enumerates handlers then unwind dest" $
         assertEqual ""
           [bbH, bbH2, bbUnw]
           (brTargets (bb (CatchSwitch tok [bbH, bbH2] (Just bbUnw))))
       , testCase "CatchSwitch with 'unwind to caller' enumerates only handlers" $
         assertEqual ""
           [bbH, bbH2]
           (brTargets (bb (CatchSwitch tok [bbH, bbH2] Nothing)))
       , testCase "CleanupRet with unwind label exposes the unwind dest" $
         assertEqual ""
           [bbUnw]
           (brTargets (bb (CleanupRet tok (Just bbUnw))))
       , testCase "CleanupRet 'unwind to caller' has no successors" $
         assertEqual ""
           []
           (brTargets (bb (CleanupRet tok Nothing)))
       ]

  , let tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        bbA   = Named (Ident "a") :: BlockLabel
        bbB   = Named (Ident "b") :: BlockLabel
        -- A relabeller that uppercases every BlockLabel's identifier so
        -- we can assert that every lab field of a constructor was
        -- actually visited by the HasLabel instance.  (A no-op identity
        -- relabel would pass even if the instance forgot a field.)
        up :: Maybe Symbol -> BlockLabel -> Identity BlockLabel
        up _ (Named (Ident s)) = pure (Named (Ident (map toUpper s)))
        up _ a                 = pure a
        toUpper c | c >= 'a' && c <= 'z' = toEnum (fromEnum c - 32)
                  | otherwise            = c
        go :: Instr' BlockLabel -> Instr' BlockLabel
        go = runIdentity . relabel up
    in Tasty.testGroup "HasLabel covers every SEH lab field"
       [ testCase "CatchRet destination is relabeled" $
         assertEqual ""
           (CatchRet tok (Named (Ident "A")))
           (go (CatchRet tok bbA))
       , testCase "CatchSwitch handlers + unwind are all relabeled" $
         assertEqual ""
           (CatchSwitch tok
              [Named (Ident "A"), Named (Ident "B")]
              (Just (Named (Ident "A"))))
           (go (CatchSwitch tok [bbA, bbB] (Just bbA)))
       , testCase "CleanupRet Nothing unwind stays Nothing" $
         assertEqual ""
           (CleanupRet tok Nothing)
           (go (CleanupRet tok Nothing))
       , testCase "CleanupRet Just unwind is relabeled" $
         assertEqual ""
           (CleanupRet tok (Just (Named (Ident "A"))))
           (go (CleanupRet tok (Just bbA)))
       , testCase "CatchPad / CleanupPad args traversed (no lab fields)" $
         do let r1 = go (CatchPad   tok [])
                r2 = go (CleanupPad tok [])
            assertEqual "CatchPad"   (CatchPad   tok []) r1
            assertEqual "CleanupPad" (CleanupPad tok []) r2
       ]

  , let tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        fnTy  = FunTy (PrimType Void) [] False
        fnPtr = ValSymbol (Symbol "callee")
        bbA   = Named (Ident "a") :: BlockLabel
        bbB   = Named (Ident "b") :: BlockLabel
        funBd = OperandBundle "funclet" [tok]
        up :: Maybe Symbol -> BlockLabel -> Identity BlockLabel
        up _ (Named (Ident s)) = pure (Named (Ident (map toUpper s)))
        up _ a                 = pure a
        toUpper c | c >= 'a' && c <= 'z' = toEnum (fromEnum c - 32)
                  | otherwise            = c
        go :: Instr' BlockLabel -> Instr' BlockLabel
        go = runIdentity . relabel up
    in Tasty.testGroup "Operand bundles + relabel"
       [ -- The bundle list itself contains no labels (the funclet
         -- token's value is an Ident not a BlockLabel), so we just
         -- assert that bundle traversal is wired in and doesn't
         -- accidentally drop the bundle.
         testCase "Call preserves its operand bundles through relabel" $
         assertEqual ""
           (Call False fnTy fnPtr [] [funBd])
           (go (Call False fnTy fnPtr [] [funBd]))

       , testCase "Invoke relabels to/unwind and preserves bundles" $
         assertEqual ""
           (Invoke (PrimType Void) fnPtr []
              (Named (Ident "A")) (Named (Ident "B")) [funBd])
           (go (Invoke (PrimType Void) fnPtr [] bbA bbB [funBd]))

       , testCase "CallBr relabels default + indirect dests and preserves bundles" $
         assertEqual ""
           (CallBr (PrimType Void) fnPtr []
              (Named (Ident "A")) [Named (Ident "B")] [funBd])
           (go (CallBr (PrimType Void) fnPtr [] bbA [bbB] [funBd]))
       ]

  , let ppWide = T.pack . PP.renderStyle (PP.Style PP.PageMode 200 1.0)
        tokTy = PrimType Token
        tok   = Typed tokTy (ValIdent (Ident "cs"))
        fnPtr = ValSymbol (Symbol "callee")
        bbA   = Named (Ident "a") :: BlockLabel
        bbB   = Named (Ident "b") :: BlockLabel
        funBd = OperandBundle "funclet" [tok]
        deopt = OperandBundle "deopt"
                  [ Typed (PrimType (Integer 32)) (ValInteger 7)
                  , Typed (PrimType (Integer 64)) (ValInteger 99)
                  ]
        instr i = ppWide $ ppLLVM 19 $ ppInstr i
    in Tasty.testGroup "Operand bundle PP (extra)"
       [ testCase "ppOperandBundle of a multi-arg deopt" $
         assertEqLines
           (ppWide (ppLLVM 19 (ppOperandBundle deopt)))
           "\"deopt\"(i32 7, i64 99)"

       , testCase "ppOperandBundles of [] renders to the empty doc" $
         assertEqLines
           (ppWide (ppLLVM 19 (ppOperandBundles [])))
           ""

       , testCase "CallBr with funclet bundle (bundle precedes 'to')" $
         assertEqLines
           (instr (CallBr (PrimType Void) fnPtr [] bbA [bbB] [funBd]))
           "callbr void @callee() [\"funclet\"(token %cs)] to label %a [label %b]"
       ]
  ]

----------------------------------------------------------------------

assertEqLines :: T.Text -> T.Text -> IO ()
assertEqLines t1 t2 =
  unless (t1 == t2) $ assertFailure $ multiLineDiff t1 t2

-- | The multiLineDiff is another helper function that can be used to
-- format a line-by-line difference display of two Text
-- representations.  This is provided as a convenience function to
-- help format large text regions for easier comparison.

multiLineDiff :: T.Text -> T.Text -> String
multiLineDiff expected actual =
  let dl (e,a) = if e == a then db e else de " ↱" e <> "\n    " <> da " ↳" a
      db b = "|        > " <> b
      de m e = "|" <> m <> "expect> " <> e
      da m a = "|" <> m <> "actual> " <> a
      el = take 1450 (visible <$> T.lines expected)
      al = take 1450 (visible <$> T.lines actual)
      visible = T.replace " " "␠"
                . T.replace "\n" "␤"
                . T.replace "\t" "␉"
                . T.replace "\012" "␍"
      addnum :: Int -> T.Text -> T.Text
      addnum n l = let nt = T.pack (show n)
                       nl = T.length nt
                   in T.take (4 - nl) "    " <> nt <> l
      ll = T.pack . show . length
      tl = T.pack . show . T.length
      banner = "MISMATCH between "
               <> ll el <> "l/" <> tl expected <> "c expected and "
               <> ll al <> "l/" <> tl actual <> "c actual"
      diffReport = fmap (uncurry addnum) $
                   zip [1..] $ concat $
                   -- Highly simplistic "diff" output assumes
                   -- correlated lines: added or removed lines just
                   -- cause everything to shown as different from that
                   -- point forward.
                   [ fmap dl $ zip el al
                   , fmap (de "∌ ") $ drop (length al) el
                   , fmap (da "∹ ") $ drop (length el) al
                   ]
                   -- n.b. T.lines seems to consume trailing whitespace before
                   -- newlines as well.  This will show any of this whitespace
                   -- difference on the last line, but not for other lines with
                   -- whitespace.
                   <> if el == al
                      then let maxlen = max (T.length expected) (T.length actual)
                               end x = T.drop (maxlen - 5) x
                           in [ [ de "∌ ending " $ visible $ end expected ]
                              , [ da "∹ ending " $ visible $ end actual ]
                              ]
                      else mempty
      details = banner : diffReport
  in if expected == actual then "<no difference>" else T.unpack (T.unlines details)
